environment:
  matrix:
    - platform: x64
      configuration: Release
    - platform: x86
      configuration: Release

install:
  - cmd: git submodule update --init
  - ps: Install-Product node LTS x64
  - npm config set msvs_version 2015 --global
  - npm config set target_arch x64 --global
  - npm install -g node-gyp

test_script:
  - npm install
  - npm rebuild
  - npm test

after_test:
  - ./node_modules/.bin/prebuild --all --strip -u %GITHUB_TOKEN%
