platform:
  - x64
  - x86

environment:
  GITHUB_TOKEN:
    secure: 8dsj2oODP6p82OsCyVjldh0v/KktBJYWWPFWmrg+bh7y0CNpQPwtww+IjX14LMrx
  matrix:
  - nodejs_version: "12"
  - nodejs_version: "14"

install:
  - cmd: git submodule update --init
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm config set --global python 2.7
  - npm config set --global msvs_version 2015
  - npm config set --global target_arch %PLATFORM%
  - npm config set --global arch $(node -e 'console.log(process.arch)')
  - npm install -g node-gyp

build_script:
  - npm install --ignore-scripts
  - npm run rebuild

test_script:
  - npm test

deploy_script:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") {./node_modules/.bin/prebuild -t 8.0.0 -t 9.0.0 -t 10.0.0 -t 11.0.0 -t 12.0.0 -t 14.0.0 --strip -u $env:GITHUB_TOKEN}
