environment:
  matrix:
    - platform: x64
    - platform: x86

install:
  - cmd: git submodule update --init
  - ps: Install-Product node LTS $env:PLATFORM
  - npm config set msvs_version 2015 --global
  - npm config set target_arch $env:PLATFORM --global
  - npm install -g node-gyp

build_script:
  - npm install
  - npm run rebuild

test_script:
  - npm test

deploy_script:
  - if %APPVEYOR_REPO_TAG% ./node_modules/.bin/prebuild --all --strip -u %GITHUB_TOKEN%
